### ISSUE TITLE
Enable markdown linting

### ISSUE THREAD

**Issue by kadler** [IBM/ibmi-oss-docs#32]
https://github.com/marketplace/actions/markdownlint-cli

First we need to fix existing markdown lint issues, though. These are:
- [x] acscloner/README.md #33
- [x] java11/JAVA11_EARLY_ACCESS.md #34
- [x] nginx.md #35
- [x] nvm/README.md #36
- [x] porting/GOTCHAS.md #42
- [x] postgresql.md #43
- [x] README.md #44
- [x] troubleshooting/5733OPS_MIGRATION.md #45
- [x] troubleshooting/README.md #46
- [x] troubleshooting/SETTING_BASH.md #47
- [x] troubleshooting/SETTING_PATH.md #48
- [x] yum/3RD_PARTY_REPOS.md #49
- [x] yum/README.md #50

To test, install markdownlint-cli: `npm i -g markdownlint-cli` and run `markownlint-cli .`

It is likely we will need to adjust the basic markdown lint rules.

**Comment by ThePrez** [comment]
For reference (if future browsers stumble across this issue), the command is now `markdownlint`, not `markdownlint-cli`

**Comment by ThePrez** [comment]
`markdownlint` now comes out clean!
